In [1]:
import tensorflow as tf

In [7]:
# making tensor 
t1=tf.constant([2,4,5,6,77])
t2=tf.constant([3,6,6,2,99])
data=tf.fill((5,5),10)
data1=tf.ones((6,6))
data2=tf.zeros((7,7))
data3=tf.random_normal((6,6))
data4=tf.random_uniform((5,5),minval=2,maxval=5)

In [3]:
mylist=[t1,t2,data,data1,data2,data3,data4]

In [5]:
cpu_use=tf.Session()   # here we created cpu oriented sessiion
#sess=tf.InteractiveSession()  #  this spcl for jupyter notebook

In [6]:
for  i  in  mylist:
    #print(sess.run(i))
    print(i.eval())
    print('\n')

cpu_use.close()

[ 2  4  5  6 77]


[ 3  6  6  2 99]


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[-0.32423407  1.1160191  -0.02432662  0.7846484  -1.8114625  -1.7287269 ]
 [ 0.1379583   0.16855942  0.01923804  2.1526942   2.7455652   0.29423717]
 [ 0.6735686  -0.4570905  -0.6671896   1.3028225   0.60196155  0.03057816]
 [ 1.3868877   0.1875231   0.11962975 -1.3162109   0.94222885  0.47957358]
 [ 0.30188233 -0.09271103 -0.25407097  0.90055716 -1.7859086   0.6216887 ]
 [ 1.2497784   0.65804017 -0.65945536  1.1760803   0.02294818  1.7824156 ]]


[[4.614917  2.3413153 2.1756063 2.8782349 3.2785816]
 [3.9168472 2.1937537 2.2750983 2.9603457 4.58607  ]
 [3.027920

In [8]:
print(t1)

Tensor("Const_2:0", shape=(5,), dtype=int32)


In [9]:
print(type(t1))

<class 'tensorflow.python.framework.ops.Tensor'>


In [10]:
print(t2)
print(type(t2))

Tensor("Const_3:0", shape=(5,), dtype=int32)
<class 'tensorflow.python.framework.ops.Tensor'>
